#![doc = include_str!("../README.md")]
#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    clippy::all,
    reason = "generated by bindgen from the vendor C headers"
)]

// bindgen computed the layouts for this target, where the headers' `__stdcall` is the C ABI.
#[cfg(not(all(windows, target_arch = "x86_64", target_env = "msvc")))]
compile_error!("mvs-sdk-sys only supports x86_64-pc-windows-msvc");

include!("bindings.rs");
