//! Raw FFI bindings to the MVS SDK. **Internal to the crate** — never re-export.
//!
//! Contents are generated by `bindgen` and committed to `src/bindings.rs`.
//! Run `cargo build --features bindgen` to regenerate after an SDK upgrade.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    unused_imports,
    clippy::all
)]

include!("bindings.rs");
